-- Presentation view: wide balance sheet pivoted from tall fact table
-- Co-authored with CoCo

CREATE OR REPLACE VIEW FFIEC.GOLD.VW_BALANCE_SHEET AS
SELECT
  di.IDRSSD,
  di.FI_NAME,
  di.FI_STATE,
  di.FI_FILING_TYPE,
  f.PERIOD_KEY AS PERIOD_END,
  MAX(CASE WHEN f.MDRM_CODE = 'RCON2170' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_ASSETS_DOMESTIC,
  MAX(CASE WHEN f.MDRM_CODE = 'RCFD2170' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_ASSETS_CONSOLIDATED,
  MAX(CASE WHEN f.MDRM_CODE = 'RCON2200' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_DEPOSITS_DOMESTIC,
  MAX(CASE WHEN f.MDRM_CODE = 'RCFN2200' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_DEPOSITS_FOREIGN,
  MAX(CASE WHEN f.MDRM_CODE = 'RCON2948' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_LIABILITIES_DOMESTIC,
  MAX(CASE WHEN f.MDRM_CODE = 'RCFD2948' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_LIABILITIES_CONSOLIDATED,
  MAX(CASE WHEN f.MDRM_CODE = 'RCON3210' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_EQUITY_CAPITAL_DOMESTIC,
  MAX(CASE WHEN f.MDRM_CODE = 'RCFD3210' THEN f.VALUE_NUMERIC END) * 1000 AS TOTAL_EQUITY_CAPITAL_CONSOLIDATED
FROM FFIEC.GOLD.FACT_CALL_REPORT f
JOIN FFIEC.GOLD.DIM_INSTITUTION di ON f.INSTITUTION_KEY = di.INSTITUTION_KEY
GROUP BY di.IDRSSD, di.FI_NAME, di.FI_STATE, di.FI_FILING_TYPE, f.PERIOD_KEY;

COMMENT ON VIEW FFIEC.GOLD.VW_BALANCE_SHEET IS
  'Presentation view: pivots the tall fact table into a wide balance-sheet shape. Values scaled from thousands (source) to actual dollars. RCON/RCFD surfaced as separate columns, never merged.';
