-- Populate UBPR taxonomy types from Concepts.xsd landing table.
-- Run after UBPR_TAXONOMY_CONCEPTS_LANDING is loaded from @STG_TAXONOMY/ubpr/.

TRUNCATE TABLE IF EXISTS FFIEC.SILVER.UBPR_TAXONOMY_TYPES;

INSERT INTO FFIEC.SILVER.UBPR_TAXONOMY_TYPES
(MDRM_CODE, XBRL_TYPE, SUBSTITUTION_GROUP, PERIOD_TYPE, NILLABLE)
SELECT 
    f.VALUE:"@name"::VARCHAR AS MDRM_CODE
    , REPLACE(f.VALUE:"@type"::VARCHAR, 'xbrli:', '') AS XBRL_TYPE
    , f.VALUE:"@substitutionGroup"::VARCHAR AS SUBSTITUTION_GROUP
    , f.VALUE:"@xbrli:periodType"::VARCHAR AS PERIOD_TYPE
    , f.VALUE:"@nillable"::BOOLEAN AS NILLABLE
FROM FFIEC.RAW.UBPR_TAXONOMY_CONCEPTS_LANDING
    , LATERAL FLATTEN(input => RAW_XML:"$") f
WHERE f.VALUE:"@"::VARCHAR = 'element';
